version: 2.1
jobs:
  unit_test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npx jest --ci --runInBand --detectOpenHandles --forceExit --testTimeout 20000
  publish:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npm run publish

workflows:
  version: 2
  main_workflow:
    jobs:
      - unit_test:
          filters: # run for everything
            tags:
              only: /.*/
            branches:
              only: /.*/
      - publish:
          requires:
            - unit_test
          filters: # run for only semver tags
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/ # matches only "v[semver]" tags. ie. v2.3.55
            branches:
              ignore: /.*/